version: '3.0'
services:
  api:
    container_name: harper
    image: harper
    build:
      context: .
      dockerfile: Dockerfile

    env_file:
      - .env
    ports:
      - "127.0.0.1:8000:8000"
